Repository indiah444/Media-Polarisation-Project, pull requests merged in 2024-10, with the labels that each got.

#36 Schema SQL file for database.
  database/schema.sql
Labels: help wanted

#38 Shell script for connecting to database.
  database/connect.sh
Labels: enhancement

#43 Updated schema in line with changes to ERD.
  database/schema.sql
Labels: enhancement

#44 Fixing schema.sql
  database/schema.sql
Labels: enhancement

#91 Updated README with information about Dockerfile.
  fox_news_scraper/README.md
Labels: documentation

#94 Created LICENSE
  LICENSE
Labels: documentation

#97 Adding new topic to static data.
  database/schema.sql
  fox_news_scraper/test_pipeline_fn.py
Labels: enhancement

#95 Democracy Now news scraper ETL
  democracy_now_scraper/Dockerfile
  democracy_now_scraper/README.md
  democracy_now_scraper/dockerise.sh
  democracy_now_scraper/extract_dn.py
  democracy_now_scraper/load_dn.py
  democracy_now_scraper/pipeline_dn.py
  democracy_now_scraper/requirements.txt
  democracy_now_scraper/test_dummy.py
  democracy_now_scraper/test_extract_dn.py
  democracy_now_scraper/test_transform_dn.py
  democracy_now_scraper/transform_dn.py
Labels: enhancement

#100 batabase functions
  dashboard/db_functions.py
  dashboard/requirements.txt
Labels: enhancement

#109 Dockerise pipeline
  news_sentiment_analyser/Dockerfile
  news_sentiment_analyser/requirements.txt
Labels: enhancement

#108 Updated cleaning process for Fox News scraper.
  fox_news_scraper/Dockerfile
  fox_news_scraper/clean_fn.py
  fox_news_scraper/load_csv_fn.py
  fox_news_scraper/test_clean_fn.py
Labels: enhancement, testing

#113 Emailing
  daily-emailing/d_db_funcs.py
  daily-emailing/daily_email.py
  daily-emailing/html_content.py
  daily-emailing/requirements.txt
  database/schema.sql
  weekly-emailing/graphs.py
  weekly-emailing/pdf_content.py
  weekly-emailing/requirements.txt
  weekly-emailing/w_db_funcs.py
  weekly-emailing/weekly_email.py
Labels: enhancement

#114 Some leftover load csv fn unit tests
  fox_news_scraper/README.md
  fox_news_scraper/test_load_csv_fn.py
Labels: testing

#117 Terraform rework main workflow
  dashboard/dashboard.py
  dashboard/requirements.txt
  dashboard/upload_dashboard.sh
  fox_news_scraper/dockerise.sh
  fox_news_scraper/load_csv_fn.py
  news_sentiment_analyser/Dockerfile
  news_sentiment_analyser/requirements.txt
  terraform/README.md
  terraform/main.tf
  terraform/outputs.tf
  terraform/sample_images/article_scraper_democracy_now/Dockerfile
  terraform/sample_images/article_scraper_democracy_now/main.py
  terraform/sample_images/article_scraper_democracy_now/requirements.txt
  terraform/sample_images/article_scraper_fox/Dockerfile
  terraform/sample_images/article_scraper_fox/dockerise.sh
  terraform/sample_images/article_scraper_fox/main.py
  terraform/sample_images/article_scraper_fox/requirements.txt
  terraform/variables.tf
Labels: enhancement

#119 Megan dashboard
  dashboard/Home.py
  dashboard/README.md
  dashboard/d_graphs.py
  dashboard/db_functions.py
  dashboard/pages/Subscribe.py
  dashboard/pages/Topic_Filter.py
  dashboard/requirements.txt
  dashboard/verify_identity.py
Labels: enhancement

#118 Word cloud visualisations for article content.
  dashboard/requirements.txt
  dashboard/word_cloud_dashboard.py
Labels: enhancement, help wanted

#120 Visualising changes in sentiment over time for a particular topic
  dashboard/db_functions.py
  dashboard/visualise_time_changes.py
Labels: enhancement

#125 Dashboard cacheing.
  dashboard/db_functions.py
  dashboard/pages/word_cloud_dashboard.py
Labels: enhancement

#127 Updated top-level README with additional information on project.
  README.md
Labels: documentation

#128 Updated homepage for dashboard.
  dashboard/Home.py
  dashboard/pages/Subscribe.py
Labels: documentation, enhancement

#129 Added additional filters to Time change graphs and added graph
  dashboard/db_functions.py
  dashboard/pages/visualise_time_changes.py
  dashboard/visualise_time_changes.py
Labels: enhancement

#139 Readmes for emailing scripts
  daily-emailing/README.md
  weekly-emailing/README.md
Labels: documentation

#142 Update ETL pipeline readme
  news_sentiment_analyser/README.md
Labels: documentation, enhancement

#134 Added random graphs
  dashboard/d_graphs.py
  dashboard/db_functions.py
  dashboard/pages/Overview.py
  dashboard/pages/Subscribe.py
Labels: enhancement

#146 Update email
  daily-emailing/d_db_funcs.py
  daily-emailing/daily_email.py
  daily-emailing/html_content.py
Labels: enhancement

#145 Updated time change dashboard page
  dashboard/d_graphs.py
  dashboard/pages/Sentiment_Over_Time.py
  dashboard/pages/visualise_time_changes.py
Labels: enhancement

#148 Shayak standardise readmes
  .github/workflows/daily_email_generator_quality copy.yml
  .github/workflows/weekly_email_generator_quality.yml
  README.md
  assets/DN_logo.png
  assets/FN_logo.png
  daily-emailing/README.md
  daily-emailing/requirements.txt
  daily-emailing/test_dummy.py
  dashboard/README.md
  dashboard/requirements.txt
  database/README.md
  database/requirements.txt
  democracy_now_scraper/README.md
  democracy_now_scraper/requirements.txt
  email_generator/README.md
  email_generator/requirements.txt
  email_generator/test_dummy.py
  fox_news_scraper/README.md
  fox_news_scraper/requirements.txt
  news_sentiment_analyser/README.md
  news_sentiment_analyser/requirements.txt
  terraform/README.md
  terraform/main.tf
  terraform/variables.tf
  weekly-emailing/README.md
  weekly-emailing/test_dummy.py
Labels: documentation

#151 Updating dashboard
  dashboard/Home.py
  dashboard/db_functions.py
  dashboard/pages/word_cloud_dashboard.py
Labels: enhancement

#158 Update time change dashboard page
  dashboard/d_graphs.py
  dashboard/pages/Sentiment_Over_Time.py
Labels: enhancement

#166 Fixing wordcloud
  dashboard/pages/5_Word_Clouds.py
Labels: enhancement

#169 Dashboard fixes - colour
  dashboard/pages/3_Sentiment_Over_Time.py
Labels: enhancement

#177 Updating dashboard homepage - colours and links
  dashboard/1_Home.py
Labels: enhancement

#178 Fixing heatmap weekday order and split into weeks
  dashboard/pages/3_Sentiment_Over_Time.py
Labels: enhancement

#170 added link to unsubscribe
  daily-emailing/README.md
  daily-emailing/d_db_funcs.py
  daily-emailing/html_content.py
  daily-emailing/test_d_db_funcs.py
  daily-emailing/test_html_content.py
Labels: enhancement

#181 Added lemmatization to word cloud
  dashboard/pages/5_Word_Clouds.py
Labels: enhancement

#189 Added topic filtering to word clouds.
  dashboard/pages/5_Word_Clouds.py
Labels: enhancement

#188 Added unit tests for some of the functions in d_graphs
  dashboard/test_d_graphs.py
Labels: enhancement

#194 Refactoring sentiment over time and fixing the granularity setting
  dashboard/d_graphs.py
  dashboard/pages/3_Sentiment_Over_Time.py
Labels: enhancement

#196 Updates to word clouds.
  dashboard/pages/5_Word_Clouds.py
Labels: enhancement

#198 Made colour gradients on heatmaps consistent
  dashboard/d_graphs.py
Labels: enhancement

#200 Refactored code on line graphs pages
  dashboard/db_functions.py
  dashboard/pages/3_Sentiment_Over_Time.py
Labels: enhancement

#203 Refactoring word clouds
  dashboard/pages/5_Word_Clouds.py
Labels: enhancement

#204 Clean files and test streamlit
  dashboard/dataframe_functions.py
  dashboard/db_functions.py
  dashboard/pages/3_Sentiment_Over_Time.py
  dashboard/pages/5_Word_Clouds.py
  dashboard/test_streamlit_pages.py
Labels: enhancement, testing

#206 Fixed small typo
  dashboard/pages/5_Word_Clouds.py
Labels: bug

#205 Added unit tests
  dashboard/dataframe_functions.py
  dashboard/test_dataframe_functions.py
Labels: enhancement, testing

#213 Fixed dashboard formatting
  dashboard/d_graphs.py
  dashboard/pages/3_Sentiment_Over_Time.py
  dashboard/pages/5_Word_Clouds.py
  dashboard/streamlit_components.py
  dashboard/test_streamlit_pages.py
Labels: enhancement

#218 Addded two unit tests to dataframe_functions
  dashboard/conftest.py
  dashboard/test_dataframe_functions.py
Labels: testing

#219 Removed unnecessary titles on word clouds.
  dashboard/pages/5_Word_Clouds.py
Labels: enhancement

#221 Updated dashboard layout.
  dashboard/1_Home.py
  dashboard/pages/3_Sentiment_Over_Time.py
  dashboard/pages/4_Topic_Filter.py
  dashboard/pages/5_Word_Clouds.py
  dashboard/pages/6_Subscribe.py
Labels: enhancement

#222 Add table of contents to the main README
  README.md
Labels: documentation

#220 Readme double check
  daily-emailing/README.md
  dashboard/d_graphs.py
  dashboard/dataframe_functions.py
  dashboard/pages/3_Sentiment_Over_Time.py
  dashboard/pages/5_Word_Clouds.py
  dashboard/test_dataframe_functions.py
  dashboard/test_streamlit_pages.py
  democracy_now_scraper/README.md
  fox_news_scraper/README.md
  news_sentiment_analyser/README.md
  news_sentiment_analyser/sentiment_analysis.py
  terraform/README.md
  terraform/main.tf
  terraform/variables.tf
  weekly-emailing/graphs.py
  weekly-emailing/pdf_content.py
Labels: documentation, enhancement

#224 Please merge. Fix Fox news issue
  fox_news_scraper/load_csv_fn.py
Labels: bug

#225 readme update
  news_sentiment_analyser/README.md
  news_sentiment_analyser/extract_s3.py
  news_sentiment_analyser/test_extract_s3.py
Labels: documentation, enhancement

#226 Updated time selector on word clouds
  dashboard/pages/5_Word_Clouds.py
Labels: enhancement
